### ISSUE TITLE
[1][Medium][App] When a user subscribes, reset their usage quota

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-server-issues-public#1]
Currently when a user subscribes and converts from free trial, their free trial used credits is still counted in their new subscribed plan. We should change it so that their credits reset to 0. This will involve Redis (their quota count is stored there).

We should gather some analytics as part of this reset process:
Data to store at the moment when they switch from free trial to Pro. This will help us gather analytics such as number of conversions, or when do users switch from free trial to Pro.
- Number of requests used
- PearAI credits used

**Comment by Fryingpannn** [comment]
@spaceonyx yo are u still working on this 👀
