### ISSUE TITLE
Auto-updates for app

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-server-issues-public#14]
When we have a new release, we want whoever who has PearAI downloaded to have a popup in the bottom right to update the app!

**Comment by Zhethan** [comment]
put me in coach

**Comment by nang-dev** [comment]
ZHETHAN GOAT

**Comment by mmiraly** [comment]
let me write 1 comment so i can put "Summer SWE Intern" on my resume

**Comment by Zhethan** [comment]
@aura0003 i got u ma boi

**Comment by Zhethan** [comment]
@nang-dev @Fryingpannn Do y'all have an endpoint to get/download the most recent releases?

**Comment by SiphamandlaMbuyazi** [comment]
> let me write 1 comment so i can put "Summer SWE Intern" on my resume
> 

Co ask

**Comment by nang-dev** [comment]
Not currently. I'm wondering if so far you found where the vscode fork is doing this currently? Does it just ping this endppoint If not i can take a look too.


Also are you planning on using electron-updater?

**Comment by nang-dev** [comment]
Zhethan — Yesterday at 5:31 PM
ye lemme link you to relevant parts of the code
https://github.com/trypear/pearai-app/blob/main/src/vs/platform/update/electron-main/abstractUpdateService.ts#L17
https://github.com/trypear/pearai-app/blob/main/src/vs/platform/update/electron-main/updateService.darwin.ts#L76
https://github.com/trypear/pearai-app/blob/main/src/vs/platform/update/electron-main/abstractUpdateService.ts#L17ye 

https://github.com/trypear/pearai-app/blob/main/src/vs/platform/update/electron-main/updateService.darwin.ts#L76
GitHub
[pearai-app/src/vs/platform/update/electron-main/updateService.darwi...](https://github.com/trypear/pearai-app/blob/main/src/vs/platform/update/electron-main/updateService.darwin.ts)
An Open Sourced AI-Powered Text Editor. A fork of VSCode and Continue. - trypear/pearai-app
pearai-app/src/vs/platform/update/electron-main/updateService.darwi...
GitHub
[pearai-app/src/vs/platform/update/electron-main/abstractUpdateServi...](https://github.com/trypear/pearai-app/blob/main/src/vs/platform/update/electron-main/abstractUpdateService.ts)
An Open Sourced AI-Powered Text Editor. A fork of VSCode and Continue. - trypear/pearai-app
pearai-app/src/vs/platform/update/electron-main/abstractUpdateServi...
So the vscode fork currently already uses electron-updater, and handles automatic updates by scheduling hourly update checks (https://github.com/trypear/pearai-app/blob/main/src/vs/platform/update/electron-main/abstractUpdateService.ts#L134). It builds the URL to the update endpoint based on: the OS the user is running on, release channel, and their current build commit hash 
GitHub
pearai-app/src/vs/platform/update/electron-main/abstractUpdateServi...
An Open Sourced AI-Powered Text Editor. A fork of VSCode and Continue. - trypear/pearai-app
[pearai-app/src/vs/platform/update/electron-main/abstractUpdateServi...](https://github.com/trypear/pearai-app/blob/main/src/vs/platform/update/electron-main/abstractUpdateService.ts)
so on the application side, I'm thinking this might be as easy as literally just changing up this function to redirect to Pear's update endpoint instead of vscode's

export function createUpdateURL(platform: string, quality: string, productService: IProductService): string {
    return `${productService.updateUrl}/api/update/${platform}/${quality}/${productService.commit}`;
}

**Comment by nang-dev** [comment]
Testing this now!

**Comment by nang-dev** [comment]
okay we need more work on server side

**Comment by nang-dev** [comment]
https://github.com/VSCodium/vscodium/issues/41

**Comment by nang-dev** [comment]
ok i fixed this
