### ISSUE TITLE
Bug: Calling end() on an ended span.

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-server-issues-public#2]
1. socket.send() raised exception.
2. Calling end() on an ended span.

![Screenshot 2024-09-12 at 4 04 24 PM](https://github.com/user-attachments/assets/59285145-f54a-4a3f-a512-b5aefe8c9ffe)
![Screenshot 2024-09-12 at 4 05 10 PM](https://github.com/user-attachments/assets/1f62755d-b3ce-4d67-b2fc-be4d91361efc)

Some bugs with logging?

**Comment by nang-dev** [comment]
asssigning to Ebb

**Comment by elee012345** [comment]
I'll take a look (already mentioned on discord)

**Comment by nang-dev** [comment]
tyty

**Comment by nang-dev** [comment]
hows this going?

**Comment by elee012345** [comment]
I'm confused I thought you told me to work on the other issue

**Comment by nang-dev** [comment]
@elee012345 oh sorry. please work on this one, as it is more urgent! :D Also, what is your discord username? lets talk there :D

**Comment by elee012345** [comment]
oh mb maybe I didn't clarify my discord and github usernames because we've talked before. my discord is sylesium. It's midterm season so i need to lock in this weekend, but I should be able to work on this issue after testing is over  :)

**Comment by nang-dev** [comment]
nw elee

@cqdev-co got it 🐐 actual legend
